alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'elbobokabo@gmail.com'
      smtp_auth_username: 'elbobokabo@gmail.com'
      smtp_auth_password: 'nhrt pgsw cvwsg luisz' # Code à 16 caractères de Google
      smtp_require_tls: true

    route:
      receiver: "email-notifications"
      group_by:
      - namespace
      routes:
      - receiver: "null"
        matchers:
        - alertname = "Watchdog"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

    inhibit_rules:
    - target_matchers:
      - severity =~ warning|info
      source_matchers:
      - severity = critical
      equal:
      - namespace
      - alertname

    receivers:
    - name: "null"
    - name: "email-notifications"
      email_configs:
      - to: 'elbobokabo@gmail.com'
        send_resolved: true