global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'elbobokabo@gmail.com'
  smtp_auth_username: 'elbobokabo@gmail.com'
  smtp_auth_password: 'nhrt pgsw cvwg luiz' # Requis (16 caractères sans espaces)
  smtp_require_tls: true

route:
  receiver: "email-notifications" # Vos alertes iront ici par défaut
  group_by:
  - namespace
  routes:
  - receiver: "null" # Le Watchdog reste désactivé (pour éviter le spam)
    matchers:
    - alertname = "Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

inhibit_rules:
- target_matchers:
  - severity =~ warning|info
  source_matchers:
  - severity = critical
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - severity = warning
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - alertname = InfoInhibitor
  equal:
  - namespace
- target_matchers:
  - alertname = InfoInhibitor

receivers:
- name: "null"
- name: "email-notifications"
  email_configs:
  - to: 'elbobokabo@gmail.com'
    send_resolved: true

templates:
- /etc/alertmanager/config/*.tmpl