# ==========================================
# Configuration globale d'Alertmanager
# ==========================================
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'tonemail@gmail.com'
      smtp_auth_username: 'tonemail@gmail.com'
      smtp_auth_identity: 'tonemail@gmail.com' # votre adresse email
      smtp_auth_password: 'mbckahysprushglst' # Code à 16 caractères de Google
      smtp_require_tls: true

    route:
      receiver: "email-notifications"
      group_by:
        - namespace
      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

    inhibit_rules:
      - target_matchers:
          - severity =~ warning|info
        source_matchers:
          - severity = critical
        equal:
          - namespace
          - alertname

    receivers:
      - name: "null"
      - name: "email-notifications"
        email_configs:
          - to: 'tonemail@gmail.com'
            send_resolved: true

# ==========================================
# Injection des Règles d'Alertes Personnalisées
# ==========================================
additionalPrometheusRulesMap:
  alerte-crash:
    groups:
      - name: crash-rules
        rules:
          - alert: CrashApp
            expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Problème dans l’app !"
              description: "L’app a planté plus de 2 fois en 5 minutes."